version: "2"

formatters:
  enable:
    - gofumpt
    - goimports

linters:
  # Default linters (errcheck, govet, ineffassign, staticcheck, unused)
  # are always enabled. Add extras here.
  enable:
    - errorlint
    - misspell
    - gocritic
    - revive
    - unconvert
    - unparam

  settings:
    misspell:
      locale: US

  exclusions:
    rules:
      # Copied verbatim from gastown upstream — lint upstream, not the copy.
      - path: internal/dolt/doltserver\.go
        linters:
          - errcheck
          - errorlint
          - staticcheck
          - gocritic
          - revive
          - unused
          - unparam
      - path: internal/dolt/rollback\.go
        linters:
          - errcheck
          - errorlint
          - staticcheck
          - gocritic
          - revive
          - unused
          - unparam
      # exec is an established package name — renaming would break imports.
      - path: internal/session/exec/
        linters:
          - revive
        text: "var-naming"
      - path: internal/beads/exec/
        linters:
          - revive
        text: "var-naming"
